services:
  cs2-medal-parser:
    build: .
    container_name: cs2-medal-parser
    volumes:
      # Persistent data storage for medals and API responses
      - ./data/:/app/data/
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
